spring:
  application:
    name: SERVICIO-SINCRONIZACION
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
server:
  port: 0

reloj:
  intervalo: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}