# Deployment para Eureka Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: aplicacion-distribuida
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: oppadev/ms-eureka-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "eureka-server"
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8761
        #   initialDelaySeconds: 90
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8761
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   timeoutSeconds: 5
---
# Service para Eureka Server
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: aplicacion-distribuida
spec:
  selector:
    app: eureka-server
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  type: NodePort