# Deployment para MS Autorización
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-autorizacion
  namespace: aplicacion-distribuida
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-autorizacion
  template:
    metadata:
      labels:
        app: ms-autorizacion
    spec:
      containers:
      - name: ms-autorizacion
        image: oppadev/ms-autorizacion:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: "SERVICIO-AUTORIZACION"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/autorizacion_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin12345"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: JWT_SECRET
          value: "a-string-secret-at-least-256-bits-long"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m -Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/ -Dserver.port=8080 -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path=/actuator"
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
# Health checks temporalmente deshabilitados por problema con JWT filter
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 90
        #   periodSeconds: 10
        #   timeoutSeconds: 5
---
# Service para MS Autorización
apiVersion: v1
kind: Service
metadata:
  name: ms-autorizacion
  namespace: aplicacion-distribuida
spec:
  selector:
    app: ms-autorizacion
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP