# Deployment para MS Catálogo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-catalogo
  namespace: aplicacion-distribuida
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-catalogo
  template:
    metadata:
      labels:
        app: ms-catalogo
    spec:
      containers:
      - name: ms-catalogo
        image: oppadev/ms-catalogo:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: "SERVICIO-CATALOGO"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/catalogo_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin12345"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "admin"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "admin"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m -Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/ -Dserver.port=8080"
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
---
# Service para MS Catálogo
apiVersion: v1
kind: Service
metadata:
  name: ms-catalogo
  namespace: aplicacion-distribuida
spec:
  selector:
    app: ms-catalogo
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP